"""add role column

Revision ID: 2737f1baf750
Revises: 2e1f94a3043a
Create Date: 2021-04-30 10:16:00.548234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2737f1baf750'
down_revision = '2e1f94a3043a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('Admin', 'User', name='role'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
